#!/usr/bin/env python3

import sys
import os
import helpers

from analyzer import Analyzer
from termcolor import colored


def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        print("Usage: ./tweets username (no preceding @)")
        exit(1)

    # get user's 50 most recent tweets
    USERNAME = sys.argv[1]
    tweets = helpers.get_user_timeline(USERNAME, 50)

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # look at each tweet
    for tweet in tweets:

        # instantiate analyzer
        analyzer = Analyzer(positives, negatives)

        # analyze tweet
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(":) {}".format(tweet), "green"))
        elif score < 0.0:
            print(colored(":( {}".format(tweet), "red"))
        else:
            print(colored(":| {}".format(tweet), "yellow"))


if __name__ == "__main__":
    main()
