# Introduction to Computer Science

- Computational thinking: how do you solve a problem
- Inputs → Algorithm (set of instructions for solving problems) → Outputs

## Inputs

### Binary

- 0,1 as opposed to decimal systems
- Place value
- Powers of 2: 1, 2, 4, 8, ...
- Bit = binary digit, 0 and 1

### ASCII

- 65 = A
- 72 73 33 - HI!

Several design choices were made, for example, you only need to flip one bit to switch from uppercase to lowercase or vice versa.

### More

- 1 byte = 8 bits
- Colors, images, video, audio

## Algorithms

- Finding someone in a phonebook
- page by page: n
- two pages: 2n (but how might skip over)
- halving: log(n)
- Only 32 steps to search through 4 billion pages!

### Code

-  **Functions** = "do this", statements, procedures
-  **Conditions** = if, else; branches, decisions
-  **Loop** = "go to"
-  **Boolean expressions** = yes or no, true or false
-  **Variables** = symbolic value
-  **Array** = multiple values

### Precision

Be precise! Be exact when programming! Computers can't make assumptions.
